server:
  port: 8080

spring:
  application:
    name: spring-security-users-authentication-authorities
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
#  sql:
#    init:
#      mode: always
#      schema-locations: classpath:org/springframework/batch/core/schema-drop-postgresql.sql
#  batch:
#    jdbc:
#      initialize-schema: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: true #SQL 실행문 로그로 기록
    properties:
      hibernate:
        ddl-auto: false
        format_sql: true #pretty format
        highlight_sql : true #colored

logging:
  level:
    org.springframework.batch.item.database: INFO ##DEBUG
